# Generated by Django 6.0.2 on 2026-04-19 04:52

import sugar.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='price_type',
            field=models.CharField(choices=[('local', 'Local'), ('premium', 'Premium')], default='local', max_length=10),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(storage=sugar.storage.DatasetStorage(), upload_to=''),
        ),
    ]
