# Generated by Django 6.0.2 on 2026-04-19 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0002_uploadedfile_price_type_alter_uploadedfile_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='price_type',
            field=models.CharField(choices=[('local', 'Local'), ('premium', 'Premium')], max_length=10),
        ),
    ]
