# Generated by Django 6.0.2 on 2026-04-19 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sugar', '0003_alter_uploadedfile_price_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='price_type',
            field=models.CharField(choices=[('local', 'Local'), ('premium', 'Premium')], default='local', max_length=10),
        ),
    ]
